version: '3.8'

services:
  key-aggregation-server:
    build: ./key-aggregation-server
    ports:
      - "8080:8080"
    environment:
      NUM_CLIENTS: 10
      HOST: 0.0.0.0
      PORT: 8080
      PRESHARED_SECRET: my_secure_presHared_secret_123!
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    # volumes:
    #   - ./redis_data:/data