
x-defaults: &default-settings
  HOST: 0.0.0.0
  NUM_CLIENTS: 2
  PRESHARED_SECRET: my_secure_presHared_secret_123!
  PORT: 8080

services:
  key-distribution-server:
    build: ./key-distribution-server
    ports:
      - "8080:8080"
    environment:
      <<: *default-settings

  fl-server:
    build: ./fl-server
    ports:
      - "8081:8081"
    environment:
      <<: *default-settings
      PORT: 8081